{{- if not .Values.controller.license.existingSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: marvinjs-license
data:
  license-key: {{ .Values.controller.license.licenseKey | b64enc | quote }}
  license-server: {{ .Values.controller.license.licenseServer | default "https://license.chemaxon.com/" | b64enc | quote }}
{{- end }}
{{- if not .Values.controller.imageCredentials.existingSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: marvinjs-image-credentials
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "marvinjs.v1.imagePullSecret" . }}
{{- end }}
